---
title: "R-club-May-3"
author: "Chunmei Li"
date: "042817"
output: 
  html_document: 
    keep_md: yes
---

```{r}
library(ggplot2)
# left
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

# right
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```

```{r}
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
              
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
    
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, group = drv)
  )# is there any difference between the last 2 ??
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth()
```

```{r}
library(tidyverse)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)

# why I can't get this plot??

```

3.6.1 Exercise
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_line() + geom_boxplot(aes(color=year))+geom_area()# for drawing a line chart

# geom_boxplot() for drawing boxplot
# geom_histogram for drawing histogram
# for area chart
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class))+geom_area(aes(color=drv))

#2. I thought this code woud draw a line with three color... but draw three lines with different color
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point() + 
  geom_smooth(se = FALSE)
#3. any difference by removing show.legend???? `geom_smooth()` using method = 'loess'

ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv), show.legend=FALSE) + 
  geom_point() + 
  geom_smooth(se = FALSE)
```
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv), show.legend=FALSE) + 
  geom_point() + 
  geom_smooth(se = FALSE)

#remove show.legend=FALSE ? why I didn't see difference. show.legend=FALSE romove the legend of graph
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point() + 
  geom_smooth()
#se argument means show or do not show standard error.


```
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

ggplot() + 
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))


# same graph, but geom_point and geom_smooth plot the same data, so they produce the same graph??
```

```{r}
#6.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(size=5) + 
  geom_smooth(se=F,size=3)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(size=5) + 
  geom_smooth(aes(group=drv),se=F, size=3)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color=drv)) + 
  geom_point(size=5) + 
  geom_smooth(se=F, size=3)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(aes(color=drv),size=5) + 
  geom_smooth(se=F, size=3)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(aes(color=drv),size=5) + 
  geom_smooth(aes(linetype=drv), se=F, size=3)
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(aes(color=drv),size=5) + 
  geom_smooth(aes(linetype=drv), se=F, size=3)

#don't know
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(aes(color=drv),size=5, shape=21)
```

3.7
```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))
```


```{r}
ggplot(data = diamonds) + 
  stat_count(mapping = aes(x = cut))
```

```{r}

#can't install packages, can install now
#install.packages("tibble")
#library(tibble)
#demo <- tribble(
 # ~a,      ~b,
  #"bar_1", 20,
  #"bar_2", 30,
  #"bar_3", 40
#)

#ggplot(data = demo) +
 #geom_bar(mapping = aes(x = a, y = b), stat = "identity")
```

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))
```

```{r}
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```

3.7.1 Exercise
```{r}
#1
ggplot(data = diamonds) + 
  stat_summary(aes(x = cut, y = depth)) # the default geom is geom_point

# rewrite by geom function
ggplot(data=diamonds)+geom_point(aes(x=cut,y=depth), stat = "summary")
#2 the defalt stat in geom_col is stat_identity 
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y=depth),stat = "identity")

ggplot(data = diamonds) + 
  geom_col(mapping = aes(x = cut, y=depth))
#3 
#4 y predicted value, ymin lower pointwise confidence interval around the mean, ymax uupper pointwise confidence interval around the mean, se standard error.
#5 there is no refference without group=1
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = ..prop..))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop..))
```
3.8

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, colour = cut))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))

ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity")

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")
```

3.8 Exercise
```{r}
#1
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_point(position = "jitter")
#2 width and heigh

ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_point()+ geom_jitter(width = 0.5, height = 1)
#3 compare geom_jitter and geom_count
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + geom_jitter()
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + geom_count()
#geom_jitter jitter every point, geom_count depend on the total amount that the value of each combination appeared.

#4 the default poistion of geom_boxplot is dodge 
ggplot(data = mpg) + 
  geom_boxplot(mapping = aes(x = displ, y = hwy, group=drv))

```

3.9
```{r}
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() +
  coord_flip()
```

```{r}
library(maps)
nz <- map_data("nz")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_quickmap()
```

```{r}
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)
bar
bar + coord_flip()
bar + coord_polar()
```

3.9 Exercise
```{r}
#1
ggplot(data = mpg) + 
  geom_bar(mapping = aes(x = drv, fill = drv))+coord_polar()
#2labs lalel the axis of the graph
#3 coor_map have correct mercator projection, coor_quickmap have the aspect ratio approximation???
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_quickmap()
library(mapproj)
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_map()
#4
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point()
#geom_abline add reference lines.
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() + 
  geom_abline()
#coord_fixed: The default, ratio = 1, ensures that one unit on the x-axis is the same length as one unit on the y-axis
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() + 
  geom_abline() +
  coord_fixed()

```


```{r}
library(tidyverse)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

filter(mpg, cyl == 8)
filter(diamonds, carat > 3)
```



my own data
```{r}
getwd()
leaf.data <- read.csv("D:/lllll/20161025-/myc2_020317 - Sheet1.csv")
ggplot(data=leaf.data)+geom_bar(aes(x=genotype, y=petioleLength, fill=treatment), stat="summary",position="dodge")
```

